In [1]:
!pip install bs4
!pip install requests

Requirement already satisfied: bs4 in c:\programdata\anaconda3\lib\site-packages (0.0.1)
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (from bs4) (4.10.0)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.2.1)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (2.26.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests) (1.26.7)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests) (3.2)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from requests) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests) (2021.10.8)

In [2]:
from bs4 import BeautifulSoup
import requests

In [3]:
page =requests.getpage =requests.get('https://www.icc-cricket.com/rankings/womens/player-rankings/odi/batting')

In [4]:
page

In [5]:
soup=BeautifulSoup(page.content)
soup2=BeautifulSoup(page.content)

In [6]:
name= []
for ODI_Batsman in soup.find_all('div',class_="rankings-block__banner--name-large"):
    name.append(ODI_Batsman.text)


for ODI_Batsman in soup2.find_all('tr',class_="table-body"):
    name.append(ODI_Batsman.a.text)    
name

['Alyssa Healy',
 'Natalie Sciver',
 'Beth Mooney',
 'Laura Wolvaardt',
 'Meg Lanning',
 'Rachael Haynes',
 'Mithali Raj',
 'Amy Satterthwaite',
 'Smriti Mandhana',
 'Tammy Beaumont',
 'Ellyse Perry',
 'Deandra Dottin',
 'Stafanie Taylor',
 'Harmanpreet Kaur',
 'Heather Knight',
 'Amelia Kerr',
 'Sophie Devine',
 'Lizelle Lee',
 'Mignon du Preez',
 'Suzie Bates',
 'Hayley Matthews',
 'Marizanne Kapp',
 'Sune Luus',
 'Ashleigh Gardner',
 'Danielle Wyatt',
 'Bismah Maroof',
 'Amy Jones',
 'Maddie Green',
 'Deepti Sharma',
 'Fargana Hoque',
 'Aliya Riaz',
 'Tahlia McGrath',
 'Chloe-Lesleigh Tryon',
 'Nahida Khan',
 'Gaby Lewis',
 'Sophia Dunkley',
 'Poonam Raut',
 'Nida Dar',
 'Katey Martin',
 'Yastika Bhatia',
 'Javeria Khan',
 'Laura Delany',
 'Dane van Niekerk',
 'Rumana Ahmed',
 'Shafali Verma',
 'Shemaine Campbelle',
 'Umaima Sohail',
 'Katherine Brunt',
 'Brooke Halliday',
 'Richa Ghosh',
 'Jess Jonassen',
 'Trisha Chetty',
 'Sidra Ameen',
 'Lauren Winfield',
 'Sharmin Supta',
 'Jhulan Goswami',
 'Nigar Sultana',
 'Muneeba Ali',
 'Salma Khatun',
 'Leah Paul',
 'Chedean Nation',
 'Pooja Vastrakar',
 'Lata Mondal',
 'Lauren Down',
 'Lara Goodall',
 'Katie Perkins',
 'Nicola Carey',
 'Sophie Ecclestone',
 'Kycia Knight',
 'Murshida Khatun',
 'Shamima Sultana',
 'Mary Waldron',
 'Mary-Anne Musonda',
 'Shikha Pandey',
 'Annabel Sutherland',
 'Jess Kerr',
 'Tazmin Brits',
 'Kate Cross',
 'Ritu Moni',
 'Amy Hunter',
 'Jemimah Rodriques',
 'Kyshona Knight',
 'Josephine Nkomo',
 'Sabbhineni Meghana',
 'Eimear Richardson',
 'Sneh Rana',
 'Lea Tahuhu',
 'Priya Punia',
 'Hayley Jensen',
 'Rajeshwari Gayakwad',
 'Andrie Steyn',
 'Shauna Kavanagh',
 'Nashra Sandhu',
 'Diana Baig',
 'Anya Shrubsole',
 'Orla Prendergast',
 'Charlotte Dean',
 'Meghna Singh',
 'Sharne Mayers',
 'Megan Schutt']

In [7]:
team= []
for ODI_Batsman in soup.find_all('div',class_="rankings-block__banner--nationality"):
    team.append(ODI_Batsman.text.replace('\n','').replace(' ',''))


for ODI_Batsman in soup2.find_all('td',class_="table-body__cell nationality-logo rankings-table__team"):
    team.append(ODI_Batsman.find('span',class_="table-body__logo-text").text)    
team

['AUS',
 'ENG',
 'AUS',
 'SA',
 'AUS',
 'AUS',
 'IND',
 'NZ',
 'IND',
 'ENG',
 'AUS',
 'WI',
 'WI',
 'IND',
 'ENG',
 'NZ',
 'NZ',
 'SA',
 'SA',
 'NZ',
 'WI',
 'SA',
 'SA',
 'AUS',
 'ENG',
 'PAK',
 'ENG',
 'NZ',
 'IND',
 'BAN',
 'PAK',
 'AUS',
 'SA',
 'PAK',
 'IRE',
 'ENG',
 'IND',
 'PAK',
 'NZ',
 'IND',
 'PAK',
 'IRE',
 'SA',
 'BAN',
 'IND',
 'WI',
 'PAK',
 'ENG',
 'NZ',
 'IND',
 'AUS',
 'SA',
 'PAK',
 'ENG',
 'BAN',
 'IND',
 'BAN',
 'PAK',
 'BAN',
 'IRE',
 'WI',
 'IND',
 'BAN',
 'NZ',
 'SA',
 'NZ',
 'AUS',
 'ENG',
 'WI',
 'BAN',
 'BAN',
 'IRE',
 'ZIM',
 'IND',
 'AUS',
 'NZ',
 'SA',
 'ENG',
 'BAN',
 'IRE',
 'IND',
 'WI',
 'ZIM',
 'IND',
 'IRE',
 'IND',
 'NZ',
 'IND',
 'NZ',
 'IND',
 'SA',
 'IRE',
 'PAK',
 'PAK',
 'ENG',
 'IRE',
 'ENG',
 'IND',
 'ZIM',
 'AUS']

In [8]:
rating= []
for ODI_Batsman in soup.find_all('div',class_="rankings-block__banner--rating"):
    rating.append(ODI_Batsman.text)


for ODI_Batsman in soup2.find_all('td',class_="table-body__cell rating"):
    rating.append(ODI_Batsman.text)    
rating

['785',
 '750',
 '748',
 '722',
 '710',
 '701',
 '686',
 '681',
 '669',
 '659',
 '642',
 '625',
 '616',
 '602',
 '601',
 '597',
 '591',
 '588',
 '581',
 '568',
 '553',
 '543',
 '512',
 '506',
 '493',
 '484',
 '483',
 '474',
 '471',
 '468',
 '450',
 '445',
 '436',
 '434',
 '431',
 '426',
 '421',
 '420',
 '420',
 '407',
 '392',
 '388',
 '384',
 '382',
 '378',
 '376',
 '376',
 '373',
 '346',
 '346',
 '339',
 '335',
 '333',
 '331',
 '330',
 '328',
 '326',
 '322',
 '321',
 '317',
 '316',
 '304',
 '297',
 '294',
 '294',
 '293',
 '271',
 '268',
 '263',
 '252',
 '248',
 '248',
 '242',
 '242',
 '241',
 '238',
 '238',
 '235',
 '229',
 '228',
 '223',
 '223',
 '221',
 '217',
 '217',
 '216',
 '213',
 '212',
 '212',
 '209',
 '208',
 '207',
 '198',
 '197',
 '197',
 '193',
 '192',
 '191',
 '191',
 '191']

In [9]:
print(len(name),len(team),len(rating))

100 100 100

In [10]:
import pandas as pd
df = pd.DataFrame({})
df['Name']=name[:10]
df['Team']=team[:10]
df['Rating']=rating[:10]
df

                Name Team Rating
0       Alyssa Healy  AUS    785
1     Natalie Sciver  ENG    750
2        Beth Mooney  AUS    748
3    Laura Wolvaardt   SA    722
4        Meg Lanning  AUS    710
5     Rachael Haynes  AUS    701
6        Mithali Raj  IND    686
7  Amy Satterthwaite   NZ    681
8    Smriti Mandhana  IND    669
9     Tammy Beaumont  ENG    659